spring:
  application:
  name: hao-ai-code
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hao-ai-code
    username: root
    password: 12345678

server:
  port: 8123
  servlet:
    context-path: /api

knife4j:
  basic:
    enable: true
  setting:
    language: zh_cn

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-a71d3c327e5e4475b7954039dc2ed77b
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-a71d3c327e5e4475b7954039dc2ed77b
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
